-- Time tracking schema on the Tools Hub Supabase project.
-- Run this entire file in the Hub SQL editor (single paste).
--
-- Note: PostgreSQL reserves ROLE and TYPE — time_entries uses quoted column names "role" and "type".
-- PostgREST / the app still see them as role and type in JSON.

-- ---------------------------------------------------------------------------
-- Base tables
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.employees (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person text NOT NULL UNIQUE,
  photo_url text,
  active boolean NOT NULL DEFAULT true,
  start_date date,
  end_date date,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.stat_holidays (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL,
  holiday_name text NOT NULL,
  jurisdiction text,
  holiday_type text,
  counts_as_working_day boolean NOT NULL DEFAULT false,
  source_url text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.employee_schedules (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person text NOT NULL REFERENCES public.employees (person) ON UPDATE CASCADE,
  effective_start_date date,
  effective_end_date date,
  monday boolean NOT NULL DEFAULT true,
  tuesday boolean NOT NULL DEFAULT true,
  wednesday boolean NOT NULL DEFAULT true,
  thursday boolean NOT NULL DEFAULT true,
  friday boolean NOT NULL DEFAULT true,
  saturday boolean NOT NULL DEFAULT false,
  sunday boolean NOT NULL DEFAULT false,
  daily_goal numeric NOT NULL DEFAULT 6.5,
  include_in_operations_kpi boolean NOT NULL DEFAULT true,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  employee_id bigint REFERENCES public.employees (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.time_off (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person text NOT NULL REFERENCES public.employees (person) ON UPDATE CASCADE,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reason text NOT NULL DEFAULT 'Time off',
  counts_as_working_day boolean NOT NULL DEFAULT false,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  employee_id bigint REFERENCES public.employees (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person text NOT NULL,
  date date NOT NULL,
  hours numeric NOT NULL,
  department text,
  "role" text,
  task text,
  "type" text,
  billable text,
  comments text,
  source_file text,
  source_row_number integer,
  source_month text,
  source_time_range text,
  source_status text,
  entry_hash text,
  employee_id bigint REFERENCES public.employees (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS time_entries_entry_hash_key
  ON public.time_entries (entry_hash)
  WHERE entry_hash IS NOT NULL;

-- ---------------------------------------------------------------------------
-- Analytics views (depend on time_entries)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW public.v_time_entries_clean AS
SELECT
  te.id,
  te.person,
  te.date,
  te.department,
  te."role" AS role,
  te.task,
  te."type" AS type,
  te.billable,
  te.hours,
  te.comments,
  te.created_at,
  te.source_file,
  te.source_month,
  te.source_row_number,
  te.source_status,
  te.source_time_range,
  (te.billable = 'Billable') AS is_billable,
  to_char(te.date, 'YYYY-MM') AS year_month,
  date_trunc('month', te.date::timestamp)::date AS month_start,
  COALESCE(e.active, true) AS employee_active,
  (NULLIF(btrim(te.comments), '') IS NOT NULL) AS has_comments
FROM public.time_entries te
LEFT JOIN public.employees e ON e.person = te.person;

CREATE OR REPLACE VIEW public.v_home_summary AS
SELECT
  round(sum(hours)::numeric, 2) AS tracked_hours,
  count(*)::bigint AS entries,
  count(DISTINCT person)::bigint AS people_tracked,
  round(avg(hours)::numeric, 2) AS average_entry_length,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct,
  round(
    100.0 * sum(CASE WHEN billable <> 'Billable' OR billable IS NULL THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS non_billable_pct
FROM public.time_entries;

CREATE OR REPLACE VIEW public.v_time_by_department AS
SELECT
  coalesce(department, '(none)') AS department,
  round(sum(hours)::numeric, 2) AS hours,
  count(*)::bigint AS entries,
  count(DISTINCT person)::bigint AS people,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct
FROM public.time_entries
GROUP BY 1
ORDER BY hours DESC;

CREATE OR REPLACE VIEW public.v_time_by_month AS
SELECT
  to_char(date, 'YYYY-MM') AS year_month,
  date_trunc('month', date::timestamp)::date AS month_start,
  round(sum(hours)::numeric, 2) AS hours
FROM public.time_entries
GROUP BY 1, 2
ORDER BY month_start;

CREATE OR REPLACE VIEW public.v_time_by_person AS
SELECT
  person,
  round(sum(hours)::numeric, 2) AS tracked_hours,
  count(*)::bigint AS entries,
  round(avg(hours)::numeric, 2) AS average_entry_length,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct,
  round(
    100.0 * sum(CASE WHEN billable <> 'Billable' OR billable IS NULL THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS non_billable_pct
FROM public.time_entries
GROUP BY person
ORDER BY tracked_hours DESC;

CREATE OR REPLACE VIEW public.v_time_by_role AS
SELECT
  coalesce("role", '(none)') AS role,
  round(sum(hours)::numeric, 2) AS hours,
  count(*)::bigint AS entries,
  count(DISTINCT person)::bigint AS people,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct
FROM public.time_entries
GROUP BY 1
ORDER BY hours DESC;

CREATE OR REPLACE VIEW public.v_time_by_task AS
SELECT
  coalesce(task, '(none)') AS task,
  round(sum(hours)::numeric, 2) AS hours,
  count(*)::bigint AS entries,
  count(DISTINCT person)::bigint AS people,
  count(DISTINCT department)::bigint AS departments,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct,
  round(avg(hours)::numeric, 2) AS average_entry_length
FROM public.time_entries
GROUP BY 1
ORDER BY hours DESC;

CREATE OR REPLACE VIEW public.v_time_by_type AS
SELECT
  coalesce("type", '(none)') AS type,
  round(sum(hours)::numeric, 2) AS hours,
  count(*)::bigint AS entries,
  count(DISTINCT person)::bigint AS people,
  round(
    100.0 * sum(CASE WHEN billable = 'Billable' THEN hours ELSE 0 END)
    / NULLIF(sum(hours), 0),
    1
  ) AS billable_pct
FROM public.time_entries
GROUP BY 1
ORDER BY hours DESC;

-- From supabase/views.sql (KPI views)
CREATE OR REPLACE VIEW public.v_person_daily_tracking AS
WITH bounds AS (
  SELECT min(time_entries.date) AS start_date,
         max(time_entries.date) AS end_date
  FROM time_entries
),
employee_days AS (
  SELECT e.person,
         gs.gs::date AS date
  FROM employees e
  CROSS JOIN bounds b
  CROSS JOIN LATERAL generate_series(
    GREATEST(COALESCE(e.start_date, b.start_date), b.start_date)::timestamp with time zone,
    LEAST(COALESCE(e.end_date, b.end_date), b.end_date)::timestamp with time zone,
    '1 day'::interval
  ) gs(gs)
  WHERE e.active = true OR COALESCE(e.end_date, b.end_date) >= b.start_date
),
daily_actuals AS (
  SELECT time_entries.person,
         time_entries.date,
         round(sum(time_entries.hours), 2) AS tracked_hours
  FROM time_entries
  GROUP BY time_entries.person, time_entries.date
),
scheduled AS (
  SELECT ed.person,
         ed.date,
         s.daily_goal,
         s.include_in_operations_kpi,
         CASE EXTRACT(isodow FROM ed.date)
           WHEN 1 THEN s.monday
           WHEN 2 THEN s.tuesday
           WHEN 3 THEN s.wednesday
           WHEN 4 THEN s.thursday
           WHEN 5 THEN s.friday
           WHEN 6 THEN s.saturday
           WHEN 7 THEN s.sunday
           ELSE NULL::boolean
         END AS scheduled_to_work
  FROM employee_days ed
  LEFT JOIN LATERAL (
    SELECT s_1.*
    FROM employee_schedules s_1
    WHERE s_1.person = ed.person
    ORDER BY s_1.created_at DESC NULLS LAST, s_1.id DESC
    LIMIT 1
  ) s ON true
),
labelled AS (
  SELECT s.person,
         s.date,
         COALESCE(a.tracked_hours, 0::numeric) AS tracked_hours,
         COALESCE(s.daily_goal, 0::numeric) AS daily_goal,
         COALESCE(s.include_in_operations_kpi, false) AS include_in_operations_kpi,
         COALESCE(s.scheduled_to_work, false) AS scheduled_to_work,
         (EXISTS (
           SELECT 1 FROM stat_holidays h
           WHERE h.date = s.date AND h.counts_as_working_day = false
         )) AS is_stat_holiday,
         (EXISTS (
           SELECT 1 FROM time_off t
           WHERE t.person = s.person
             AND s.date >= t.start_date AND s.date <= t.end_date
             AND t.counts_as_working_day = false
         )) AS is_time_off,
         (SELECT string_agg(DISTINCT t.reason, ', '::text)
          FROM time_off t
          WHERE t.person = s.person
            AND s.date >= t.start_date AND s.date <= t.end_date
         ) AS context
  FROM scheduled s
  LEFT JOIN daily_actuals a ON a.person = s.person AND a.date = s.date
)
SELECT person,
       date,
       tracked_hours,
       daily_goal,
       include_in_operations_kpi,
       scheduled_to_work,
       is_stat_holiday,
       is_time_off,
       context,
       CASE
         WHEN scheduled_to_work AND NOT is_stat_holiday AND NOT is_time_off THEN true
         ELSE false
       END AS counted_working_day
FROM labelled;

CREATE OR REPLACE VIEW public.v_operations_kpi AS
WITH current_schedule AS (
  SELECT DISTINCT ON (s.person)
    s.person,
    s.id AS schedule_id,
    s.include_in_operations_kpi,
    s.daily_goal,
    s.notes
  FROM employee_schedules s
  ORDER BY s.person, s.created_at DESC NULLS LAST, s.id DESC
),
eligible AS (
  SELECT e_1.person,
         cs.schedule_id,
         COALESCE(cs.include_in_operations_kpi, false) AS include_in_operations_kpi,
         COALESCE(cs.daily_goal, 6.5) AS daily_goal,
         cs.notes
  FROM employees e_1
  LEFT JOIN current_schedule cs ON cs.person = e_1.person
  WHERE e_1.active
),
daily AS (
  SELECT v.person,
         v.date,
         v.tracked_hours,
         v.daily_goal,
         v.include_in_operations_kpi,
         v.scheduled_to_work,
         v.is_stat_holiday,
         v.is_time_off,
         v.context,
         v.counted_working_day
  FROM v_person_daily_tracking v
  JOIN eligible e_1 ON e_1.person = v.person
),
median_source AS (
  SELECT d.person,
         percentile_cont(0.5::double precision)
           WITHIN GROUP (ORDER BY (d.tracked_hours::double precision)) AS median_active_day
  FROM daily d
  WHERE d.counted_working_day AND d.tracked_hours > 0::numeric
  GROUP BY d.person
),
totals AS (
  SELECT d.person,
         round(sum(d.tracked_hours), 2) AS tracked_hours,
         count(*) FILTER (WHERE d.counted_working_day) AS counted_working_days,
         round(avg(d.tracked_hours) FILTER (WHERE d.counted_working_day), 2) AS avg_working_day
  FROM daily d
  GROUP BY d.person
)
SELECT t.person,
       t.tracked_hours,
       t.counted_working_days,
       t.avg_working_day,
       round(m.median_active_day::numeric, 2) AS median_active_day,
       CASE
         WHEN e.schedule_id IS NULL THEN 'Schedule needed'::text
         WHEN e.include_in_operations_kpi = false THEN 'Not included in current KPI'::text
         WHEN NULLIF(btrim(e.notes), ''::text) IS NOT NULL THEN 'Context exception'::text
         WHEN t.counted_working_days = 0 THEN 'Needs review'::text
         WHEN t.avg_working_day >= e.daily_goal THEN 'On track'::text
         WHEN t.avg_working_day >= (e.daily_goal - 0.5) THEN 'Close to target'::text
         ELSE 'Needs review'::text
       END AS status,
       NULLIF(btrim(e.notes), ''::text) AS context
FROM totals t
JOIN eligible e ON e.person = t.person
LEFT JOIN median_source m ON m.person = t.person
ORDER BY t.avg_working_day DESC NULLS LAST;

-- ---------------------------------------------------------------------------
-- RLS — authenticated users with time-tracking tool access only
-- ---------------------------------------------------------------------------

ALTER TABLE public.employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.employee_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_off ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stat_holidays ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.time_entries ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.time_tracking_user_has_access()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.user_can_access_tool_by_slug('time-tracking');
$$;

GRANT EXECUTE ON FUNCTION public.time_tracking_user_has_access() TO authenticated;

DROP POLICY IF EXISTS time_tracking_employees_select ON public.employees;
DROP POLICY IF EXISTS time_tracking_schedules_select ON public.employee_schedules;
DROP POLICY IF EXISTS time_tracking_time_off_select ON public.time_off;
DROP POLICY IF EXISTS time_tracking_holidays_select ON public.stat_holidays;
DROP POLICY IF EXISTS time_tracking_entries_select ON public.time_entries;

CREATE POLICY time_tracking_employees_select ON public.employees
  FOR SELECT TO authenticated
  USING (public.time_tracking_user_has_access());

CREATE POLICY time_tracking_schedules_select ON public.employee_schedules
  FOR SELECT TO authenticated
  USING (public.time_tracking_user_has_access());

CREATE POLICY time_tracking_time_off_select ON public.time_off
  FOR SELECT TO authenticated
  USING (public.time_tracking_user_has_access());

CREATE POLICY time_tracking_holidays_select ON public.stat_holidays
  FOR SELECT TO authenticated
  USING (public.time_tracking_user_has_access());

CREATE POLICY time_tracking_entries_select ON public.time_entries
  FOR SELECT TO authenticated
  USING (public.time_tracking_user_has_access());

REVOKE ALL ON public.v_time_entries_clean FROM anon;
REVOKE ALL ON public.v_person_daily_tracking FROM anon;
REVOKE ALL ON public.v_operations_kpi FROM anon;
REVOKE ALL ON public.v_home_summary FROM anon;
REVOKE ALL ON public.v_time_by_department FROM anon;
REVOKE ALL ON public.v_time_by_month FROM anon;
REVOKE ALL ON public.v_time_by_person FROM anon;
REVOKE ALL ON public.v_time_by_role FROM anon;
REVOKE ALL ON public.v_time_by_task FROM anon;
REVOKE ALL ON public.v_time_by_type FROM anon;

GRANT SELECT ON public.v_time_entries_clean TO authenticated;
GRANT SELECT ON public.v_person_daily_tracking TO authenticated;
GRANT SELECT ON public.v_operations_kpi TO authenticated;
GRANT SELECT ON public.v_home_summary TO authenticated;
GRANT SELECT ON public.v_time_by_department TO authenticated;
GRANT SELECT ON public.v_time_by_month TO authenticated;
GRANT SELECT ON public.v_time_by_person TO authenticated;
GRANT SELECT ON public.v_time_by_role TO authenticated;
GRANT SELECT ON public.v_time_by_task TO authenticated;
GRANT SELECT ON public.v_time_by_type TO authenticated;

-- Next: run migrations 001–005 in order (import RPCs, employee sync, etc.).
