-- Run this if 006 failed partway and time_entries was never created.
-- Safe to run when employees already exists from a partial 006 apply.

CREATE TABLE IF NOT EXISTS public.time_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  person text NOT NULL,
  date date NOT NULL,
  hours numeric NOT NULL,
  department text,
  "role" text,
  task text,
  "type" text,
  billable text,
  comments text,
  source_file text,
  source_row_number integer,
  source_month text,
  source_time_range text,
  source_status text,
  entry_hash text,
  employee_id bigint REFERENCES public.employees (id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS time_entries_entry_hash_key
  ON public.time_entries (entry_hash)
  WHERE entry_hash IS NOT NULL;
